"""Compile promoted, non-stale facts into agent-facing context files.

Hot facts go into the always-loaded file(s) (AGENTS.md by default). Warm
facts are NOT inlined there -- they are written to per-scope files under
.seedbank/warm/ and AGENTS.md only carries a one-line pointer to each,
so the always-loaded budget stays small and warm material is loaded only
when an agent decides a task is relevant to that scope.
"""
from __future__ import annotations

from pathlib import Path

HEADER = (
    "<!-- Generated by seedbank. Do not hand-edit -- run `seedbank promote`"
    "/`demote` then `seedbank compile` to regenerate. -->\n"
    "<!-- Source of truth: .seedbank/facts.json -->\n"
)


def active_facts(facts: dict, tier: str) -> list[dict]:
    return [f for f in facts["facts"].values() if f["tier"] == tier and not f.get("stale")]


def render_agents_md(facts: dict) -> str:
    hot = active_facts(facts, "hot")
    warm = active_facts(facts, "warm")
    warm_scopes = sorted({f.get("scope", "general") for f in warm})

    lines = [HEADER, "", "## Hot context (always loaded)", ""]
    if hot:
        for f in sorted(hot, key=lambda f: f.get("scope", "general")):
            lines.append(f"- {f['representation']}  [{f.get('scope', 'general')}]")
    else:
        lines.append("_(none yet -- run `seedbank candidates` then `seedbank promote`)_")
    lines.append("")

    lines.append("## Warm context (load only when relevant to the current task)")
    lines.append("")
    if warm_scopes:
        for scope in warm_scopes:
            lines.append(f"- **{scope}**: see `.seedbank/warm/{scope}.md`")
    else:
        lines.append("_(none yet)_")
    lines.append("")
    return "\n".join(lines)


def render_warm_scope_md(scope: str, facts_for_scope: list[dict]) -> str:
    lines = [HEADER, "", f"## Warm context: {scope}", ""]
    for f in facts_for_scope:
        conf = f.get("confidence", 0.8)
        lines.append(f"- {f['representation']}  (confidence={conf:.2f})")
    lines.append("")
    return "\n".join(lines)


def compile_outputs(facts: dict, repo_root: Path, targets: list[str]) -> dict:
    """Write AGENTS.md-equivalent file(s) + warm/*.md. Returns a report dict."""
    agents_md = render_agents_md(facts)
    written = []
    for target in targets:
        path = repo_root / target
        path.write_text(agents_md)
        written.append(str(path))

    warm = active_facts(facts, "warm")
    by_scope: dict[str, list[dict]] = {}
    for f in warm:
        by_scope.setdefault(f.get("scope", "general"), []).append(f)

    warm_dir = repo_root / ".seedbank" / "warm"
    if by_scope:
        warm_dir.mkdir(parents=True, exist_ok=True)
    for scope, flist in by_scope.items():
        (warm_dir / f"{scope}.md").write_text(render_warm_scope_md(scope, flist))
        written.append(str(warm_dir / f"{scope}.md"))

    hot_tokens = sum(f["persistent_token_cost"] for f in active_facts(facts, "hot"))
    stale_excluded = [f["id"] for f in facts["facts"].values() if f.get("stale")]

    return {
        "written": written,
        "hot_fact_count": len(active_facts(facts, "hot")),
        "warm_fact_count": len(warm),
        "hot_tokens": hot_tokens,
        "stale_excluded": stale_excluded,
    }
